# -*- coding: utf-8 -*-
"""Vcodez_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1YU0J9QRgyRxVfhfZJld92ZXaTuAgH-
"""
# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Set Page Configuration
st.set_page_config(page_title="Streamlit Practice App", page_icon="📝", layout="centered")

# Title & Header
st.title("📝 Streamlit Practice App")
st.header("Welcome to Your First Streamlit App")
st.subheader("Let's Explore Streamlit Features")
st.write("This app demonstrates various Streamlit components for user inputs, outputs, charts, and file handling.")

# Text Input
name = st.text_input("Enter your name:", "Type here...")
if name and name != "Type here...":
    st.write(f"👋 Hello, {name}!")

# Number Input
age = st.number_input("Enter your age:", min_value=0, max_value=120, value=25)

# Dropdown (Selectbox)
color = st.selectbox("Choose your favorite color:", ["Red", "Blue", "Green", "Yellow", "Black"])
st.write(f"Your favorite color is **{color}**.")

# Checkbox
if st.checkbox("I agree to the terms and conditions"):
    st.success("✅ Thank you for agreeing!")

# Radio Button
status = st.radio("What is your status?", ["Student", "Working", "Other"])
st.write(f"Status: {status}")

# Slider
rating = st.slider("Rate this app:", 0, 10, 5)
st.write(f"You rated this app: {rating}/10")

# File Uploader
uploaded_file = st.file_uploader("Upload a CSV file (optional to see DataFrame preview):")
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.write("📊 Uploaded Data Preview:")
    st.dataframe(df)

# Button with Action
if st.button("Click Me!"):
    st.balloons()
    st.success("🎉 You clicked the button!")

# Chart Example
st.subheader("📈 Random Data Chart Example")
chart_data = pd.DataFrame(np.random.randn(20, 3), columns=['A', 'B', 'C'])
st.line_chart(chart_data)

# Matplotlib Plot
st.subheader("📊 Matplotlib Example")
fig, ax = plt.subplots()
ax.hist(np.random.randn(100), bins=15, color='skyblue', edgecolor='black')
st.pyplot(fig)

# Image Display
st.subheader("🖼 Displaying an Image")
st.image("https://i.postimg.cc/tgp6npLp/9h1h4y3k.png", width=300)

# Markdown Example
st.markdown("""
### About This App:
- ✅ Created using Streamlit  
- ✅ Demonstrates Inputs, Outputs, Charts, and Images  
- ✅ Deployable to Streamlit Cloud
""")

# Session State Example
if "count" not in st.session_state:
    st.session_state["count"] = 0

if st.button("Increase Counter"):
    st.session_state["count"] += 1

st.write(f"🔢 Counter Value: {st.session_state['count']}")

# Footer
st.markdown("---")
st.markdown("Made with ❤️ using Streamlit")


